// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payroll.Infrastructure.Database;

#nullable disable

namespace Payroll.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payroll.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date")
                        .HasColumnName("termination_date");

                    b.ComplexProperty<Dictionary<string, object>>("BaseSalary", "Payroll.Domain.Employee.BaseSalary#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("base_salary_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("base_salary_currency");
                        });

                    b.HasKey("EmployeeId")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.EmployeePayrollPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("OverrideRateOrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("override_rate_or_amount");

                    b.Property<Guid>("PayrollPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_policy_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_payroll_policies");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_payroll_policies_employee_id");

                    b.HasIndex("PayrollPolicyId")
                        .HasDatabaseName("ix_employee_payroll_policies_payroll_policy_id");

                    b.ToTable("employee_payroll_policies", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.PayrollPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("calculation_type");

                    b.Property<string>("CompensationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("compensation_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RateOrAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_or_amount");

                    b.HasKey("Id")
                        .HasName("pk_payroll_policies");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_payroll_policies_name");

                    b.ToTable("payroll_policies", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.ComplexProperty<Dictionary<string, object>>("Period", "Payroll.Domain.PayrollRun.Period#PayPeriod", b1 =>
                        {
                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("period_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("period_start");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalBonuses", "Payroll.Domain.PayrollRun.TotalBonuses#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_bonuses_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_bonuses_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalDeductions", "Payroll.Domain.PayrollRun.TotalDeductions#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_deductions_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_deductions_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalGross", "Payroll.Domain.PayrollRun.TotalGross#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_gross_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_gross_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalNet", "Payroll.Domain.PayrollRun.TotalNet#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_net_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_net_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_payroll_runs");

                    b.ToTable("payroll_runs", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.PayrollRunFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_run_id");

                    b.HasKey("Id")
                        .HasName("pk_payroll_run_failures");

                    b.HasIndex("PayrollRunId")
                        .HasDatabaseName("ix_payroll_run_failures_payroll_run_id");

                    b.ToTable("payroll_run_failures", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_name");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_run_id");

                    b.ComplexProperty<Dictionary<string, object>>("BaseSalary", "Payroll.Domain.Payslip.BaseSalary#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_salary_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_salary_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NetPay", "Payroll.Domain.Payslip.NetPay#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("net_pay_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("net_pay_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Period", "Payroll.Domain.Payslip.Period#PayPeriod", b1 =>
                        {
                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("period_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("period_start");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalBonuses", "Payroll.Domain.Payslip.TotalBonuses#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_bonuses_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_bonuses_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalDeductions", "Payroll.Domain.Payslip.TotalDeductions#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_deductions_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_deductions_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_payslips");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_payslips_employee_id");

                    b.HasIndex("PayrollRunId")
                        .HasDatabaseName("ix_payslips_payroll_run_id");

                    b.ToTable("payslips", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.PayslipItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompensationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("compensation_type");

                    b.Property<decimal?>("OverrideRateOrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("override_rate_or_amount");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("uuid")
                        .HasColumnName("payslip_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_name");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "Payroll.Domain.PayslipItem.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_payslip_items");

                    b.HasIndex("PayslipId")
                        .HasDatabaseName("ix_payslip_items_payslip_id");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_payslip_items_policy_id");

                    b.ToTable("payslip_items", (string)null);
                });

            modelBuilder.Entity("Payroll.Infrastructure.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_users_employee_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Payroll.Domain.Employee", b =>
                {
                    b.HasOne("Payroll.Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Payroll.Domain.EmployeePayrollPolicy", b =>
                {
                    b.HasOne("Payroll.Domain.Employee", null)
                        .WithMany("EmployeePayrollPolicies")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_payroll_policies_employees_employee_id");

                    b.HasOne("Payroll.Domain.PayrollPolicy", "PayrollPolicy")
                        .WithMany()
                        .HasForeignKey("PayrollPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_payroll_policies_payroll_policies_payroll_policy_id");

                    b.Navigation("PayrollPolicy");
                });

            modelBuilder.Entity("Payroll.Domain.PayrollRunFailure", b =>
                {
                    b.HasOne("Payroll.Domain.PayrollRun", null)
                        .WithMany("Failures")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payroll_run_failures_payroll_runs_payroll_run_id");
                });

            modelBuilder.Entity("Payroll.Domain.Payslip", b =>
                {
                    b.HasOne("Payroll.Domain.Employee", null)
                        .WithMany("Payslips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payslips_employees_employee_id");

                    b.HasOne("Payroll.Domain.PayrollRun", "PayrollRun")
                        .WithMany("Payslips")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payslips_payroll_runs_payroll_run_id");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("Payroll.Domain.PayslipItem", b =>
                {
                    b.HasOne("Payroll.Domain.Payslip", "Payslip")
                        .WithMany("Items")
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payslip_items_payslips_payslip_id");

                    b.HasOne("Payroll.Domain.PayrollPolicy", "PayrollPolicy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payslip_items_payroll_policies_policy_id");

                    b.Navigation("PayrollPolicy");

                    b.Navigation("Payslip");
                });

            modelBuilder.Entity("Payroll.Infrastructure.Auth.User", b =>
                {
                    b.HasOne("Payroll.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Domain.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Payroll.Domain.Employee", b =>
                {
                    b.Navigation("EmployeePayrollPolicies");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("Payroll.Domain.PayrollRun", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("Payroll.Domain.Payslip", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
